version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16  # Replace with your desired Node.js version
    working_directory: ~/app

jobs:
  build-node-app:
    executor: node-executor
    steps:
      - checkout
      
      # Cache Node modules to speed up subsequent builds
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
            - node-modules-
      
      - run:
          name: Install dependencies
          command: |
            mkdir -p ~/node_modules
            npm ci  # Install exact versions from package-lock.json
      
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package-lock.json" }}
      
      - persist_to_workspace:
          root: .
          paths:
            - .
      

  test-node-app:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/app  # Attach workspace at the same working directory
      
      - run:
          name: Run tests
          command: npm test  # Replace with your test script

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-node-app
      - test-node-app:
          requires:
            - build-node-app
      - synk-scan:
          requires:
            - build-node-app
      

      